export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_ADD_REQUEST = 'PRODUCT_ADD_REQUEST';
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS';
export const PRODUCT_ADD_FAIL = 'PRODUCT_ADD_FAIL';

export const PRODUCT_UPD_REQUEST = 'PRODUCT_UPD_REQUEST';
export const PRODUCT_UPD_SUCCESS = 'PRODUCT_UPD_SUCCESS';
export const PRODUCT_UPD_FAIL = 'PRODUCT_UPD_FAIL';

export const MINE_ADD_ITEM = 'CART_ADD_ITEM';
export const MINE_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const MINE_EMPTY = 'CART_EMPTY';